site_name: Graphyte Webdoc Automation
nav:
    - Home: index.md
    - Input Files:
        - Input Files: input_files.md
        - Templates:
            - Templates: templates.md
    - Output Files: output_files.md
    - Templates: templates.md
    - Diagrams: diagrams.md
    - Variable List: variables.md
    - Configuration File: configfile.md
theme: readthedocs