site_name: Graphyte Webdoc Automation
nav:
    - The Basics: index.md
    - Graphyte Step-by-Step Guide: usage.md
    - Creating Templates: templates.md
    - Creating SVG diagrams with Microsoft Visio: diagrams_visio.md
    - Creating SVG diagrams with Draw.io: diagrams_drawio.md
    - Creating SVG diagrams with Inkscape: diagrams_inkscape.md
    - Creating UML diagrams for Graphyte: diagrams_uml.md
    - Rendering YANG diagrams with Graphyte: diagrams_yang.md
    - Linking Input Diagrams and Templates: linking.md
    - Performing Variable Validation: variables.md
    - Graphyte Configuration File: configfile.md
    - Running Graphyte: running.md
    - 'Graphyte Output Files: The Model': output_files.md
    - About: about.md
theme: readthedocs