site_name: Graphyte Webdoc Automation
nav:
    - Home: index.md
    - Templates: templates.md
    - Diagrams: diagrams.md
    - Variable: variables.md
    - Configuration: configfile.md
theme: readthedocs